#ifndef UNCONDITIONALOPTIMIZATIONMETHODS_COORDINATEDESCENT_H
#define UNCONDITIONALOPTIMIZATIONMETHODS_COORDINATEDESCENT_H

class CoordinateDescent {
public:
    void coordinateDescentMethod();
};

#endif //UNCONDITIONALOPTIMIZATIONMETHODS_COORDINATEDESCENT_H