//
// Created by Анастасия on 26.05.2019.
//

#ifndef UNCONDITIONALOPTIMIZATIONMETHODS_FLETCHERREEVES_H
#define UNCONDITIONALOPTIMIZATIONMETHODS_FLETCHERREEVES_H
class FletcherReeves {
public:
    void fletcherReevesMethod();
};
#endif //UNCONDITIONALOPTIMIZATIONMETHODS_FLETCHERREEVES_H
