//
// Created by Анастасия on 26.05.2019.
//

#ifndef UNCONDITIONALOPTIMIZATIONMETHODS_GRADDESWITHCONSTSTEP_H
#define UNCONDITIONALOPTIMIZATIONMETHODS_GRADDESWITHCONSTSTEP_H
class GradDesWithConstStep {
public:
    void gradDesWithConstStepMethod();
};
#endif //UNCONDITIONALOPTIMIZATIONMETHODS_GRADDESWITHCONSTSTEP_H
