//
// Created by Анастасия on 26.05.2019.
//

#ifndef UNCONDITIONALOPTIMIZATIONMETHODS_NELDERMID_H
#define UNCONDITIONALOPTIMIZATIONMETHODS_NELDERMID_H
class NelderMid {
public:
    void nelderMidMethod();
};
#endif //UNCONDITIONALOPTIMIZATIONMETHODS_NELDERMID_H
