//
// Created by Анастасия on 26.05.2019.
//

#ifndef UNCONDITIONALOPTIMIZATIONMETHODS_NEWTONRAPHSON_H
#define UNCONDITIONALOPTIMIZATIONMETHODS_NEWTONRAPHSON_H
class NewtonRaphson {
public:
    void newtonRaphsonMethod();
};
#endif //UNCONDITIONALOPTIMIZATIONMETHODS_NEWTONRAPHSON_H
