//
// Created by Анастасия on 26.05.2019.
//

#ifndef UNCONDITIONALOPTIMIZATIONMETHODS_QUICKGRADDESCENT_H
#define UNCONDITIONALOPTIMIZATIONMETHODS_QUICKGRADDESCENT_H
class QuickGradDescent {
public:
    void quickGradDescentMethod();
};
#endif //UNCONDITIONALOPTIMIZATIONMETHODS_QUICKGRADDESCENT_H
